spring:
  application:
    name: sample
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true


URL: "https://api.postalpincode.in/pincode/CITY"